// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryptedMessage.proto

package goprocrypt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncryptedMessage struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	VerificationKeyId    []byte   `protobuf:"bytes,8,opt,name=verificationKeyId,proto3" json:"verificationKeyId,omitempty"`
	DecryptionKeyId      []byte   `protobuf:"bytes,9,opt,name=decryptionKeyId,proto3" json:"decryptionKeyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedMessage) Reset()         { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string { return proto.CompactTextString(m) }
func (*EncryptedMessage) ProtoMessage()    {}
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc45adbfce800ef5, []int{0}
}

func (m *EncryptedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedMessage.Unmarshal(m, b)
}
func (m *EncryptedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedMessage.Marshal(b, m, deterministic)
}
func (m *EncryptedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedMessage.Merge(m, src)
}
func (m *EncryptedMessage) XXX_Size() int {
	return xxx_messageInfo_EncryptedMessage.Size(m)
}
func (m *EncryptedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedMessage proto.InternalMessageInfo

func (m *EncryptedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *EncryptedMessage) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *EncryptedMessage) GetVerificationKeyId() []byte {
	if m != nil {
		return m.VerificationKeyId
	}
	return nil
}

func (m *EncryptedMessage) GetDecryptionKeyId() []byte {
	if m != nil {
		return m.DecryptionKeyId
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedMessage)(nil), "goprocrypt.EncryptedMessage")
}

func init() { proto.RegisterFile("encryptedMessage.proto", fileDescriptor_dc45adbfce800ef5) }

var fileDescriptor_dc45adbfce800ef5 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x49, 0x4d, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xcf, 0x2f, 0x28, 0xca, 0x07, 0x4b, 0x29, 0x2d, 0x60, 0xe4, 0x12,
	0x70, 0x45, 0x53, 0x26, 0x24, 0xc3, 0xc5, 0x59, 0x9c, 0x99, 0x9e, 0x97, 0x58, 0x52, 0x5a, 0x94,
	0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10, 0x10, 0x12, 0xe3, 0x62, 0x4b, 0xc9, 0x4c,
	0x4f, 0x2d, 0x2e, 0x91, 0x60, 0x06, 0x4b, 0x41, 0x79, 0x42, 0x3a, 0x5c, 0x82, 0x65, 0xa9, 0x45,
	0x99, 0x69, 0x99, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xde, 0xa9, 0x95, 0x9e, 0x29, 0x12, 0x1c,
	0x60, 0x25, 0x98, 0x12, 0x42, 0x1a, 0x5c, 0xfc, 0x29, 0xa9, 0x60, 0x7b, 0xe1, 0x6a, 0x39, 0xc1,
	0x6a, 0xd1, 0x85, 0x9d, 0x78, 0xa2, 0x90, 0x1c, 0x9c, 0xc4, 0x06, 0xf6, 0x83, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x2a, 0xd6, 0x79, 0xdd, 0x00, 0x00, 0x00,
}
