// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testMsg.proto

package goprocrypt_tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMsg struct {
	Time                 int64    `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	TrialNo              int32    `protobuf:"varint,3,opt,name=trialNo,proto3" json:"trialNo,omitempty"`
	Msgtext              string   `protobuf:"bytes,5,opt,name=msgtext,proto3" json:"msgtext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMsg) Reset()         { *m = TestMsg{} }
func (m *TestMsg) String() string { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()    {}
func (*TestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_testMsg_fbbd7a5c0336346d, []int{0}
}
func (m *TestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMsg.Unmarshal(m, b)
}
func (m *TestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMsg.Marshal(b, m, deterministic)
}
func (dst *TestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg.Merge(dst, src)
}
func (m *TestMsg) XXX_Size() int {
	return xxx_messageInfo_TestMsg.Size(m)
}
func (m *TestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg proto.InternalMessageInfo

func (m *TestMsg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TestMsg) GetTrialNo() int32 {
	if m != nil {
		return m.TrialNo
	}
	return 0
}

func (m *TestMsg) GetMsgtext() string {
	if m != nil {
		return m.Msgtext
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "goprocrypt_tests.TestMsg")
}

func init() { proto.RegisterFile("testMsg.proto", fileDescriptor_testMsg_fbbd7a5c0336346d) }

var fileDescriptor_testMsg_fbbd7a5c0336346d = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x49, 0x2d, 0x2e,
	0xf1, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x48, 0xcf, 0x2f, 0x28, 0xca,
	0x4f, 0x2e, 0xaa, 0x2c, 0x28, 0x89, 0x07, 0xc9, 0x14, 0x2b, 0x05, 0x72, 0xb1, 0x87, 0x40, 0x94,
	0x08, 0x09, 0x71, 0xb1, 0x94, 0x64, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x08, 0x04, 0x81,
	0xd9, 0x42, 0x12, 0x5c, 0xec, 0x25, 0x45, 0x99, 0x89, 0x39, 0x7e, 0xf9, 0x12, 0xcc, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x30, 0x2e, 0x48, 0x26, 0xb7, 0x38, 0xbd, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x55,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x75, 0x12, 0x8a, 0xc2, 0xb0, 0x26, 0x89, 0x0d, 0x6c, 0xbf,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x32, 0x0c, 0xc8, 0xb1, 0x90, 0x00, 0x00, 0x00,
}
